version: "3.8"

# =====================================================
# DATABASE STACK - PRODUCTION
# =====================================================
# Only MariaDB - Redis in application stack
# =====================================================

services:
  mariadb:
    image: mariadb:10.6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max-connections=500
      - --innodb-buffer-pool-size=1G
      - --innodb-log-file-size=512M
      - --innodb-flush-log-at-trx-commit=2
      - --innodb-flush-method=O_DIRECT
      - --query-cache-size=0
      - --query-cache-type=0
      - --slow-query-log=1
      - --slow-query-log-file=/var/lib/mysql/slow.log
      - --long-query-time=2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - mariadb-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb-data:
    name: brandclub-prod-mariadb

networks:
  mariadb-network:
    name: brandclub-prod-mariadb
    driver: overlay
    attachable: true

# =====================================================
# ENVIRONMENT VARIABLES REQUIRED (set in Portainer)
# =====================================================
# DB_ROOT_PASSWORD=mannan@123
