version: "3.8"

# =====================================================
# DATABASE STACK - PRODUCTION
# =====================================================
# Purpose: Isolated MariaDB and Redis for PRODUCTION environment
# Why separate: Prevents database restart on app redeployment
# Critical: Never redeploy this stack unless necessary!
# =====================================================

services:
  # ===== MariaDB Database =====
  mariadb:
    image: mariadb:10.6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      # Production Performance tuning
      - --max-connections=500
      - --innodb-buffer-pool-size=1G
      - --innodb-log-file-size=512M
      - --innodb-flush-log-at-trx-commit=2
      - --innodb-flush-method=O_DIRECT
      - --query-cache-size=0
      - --query-cache-type=0
      - --slow-query-log=1
      - --slow-query-log-file=/var/lib/mysql/slow.log
      - --long-query-time=2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - brandclub-prod-mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===== Redis Cache =====
  redis-cache:
    image: redis:6.2-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
    command:
      - redis-server
      - --maxmemory
      - 512mb
      - --maxmemory-policy
      - allkeys-lru
      - --save
      - ""
    volumes:
      - redis-cache-data:/data
    networks:
      - brandclub-prod-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ===== Redis Queue =====
  redis-queue:
    image: redis:6.2-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
    volumes:
      - redis-queue-data:/data
    networks:
      - brandclub-prod-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

# ===== Volumes =====
volumes:
  mariadb-data:
    name: brandclub-prod-db-data
  redis-cache-data:
    name: brandclub-prod-redis-cache
  redis-queue-data:
    name: brandclub-prod-redis-queue

# ===== Networks =====
networks:
  # Database network (external to app stack)
  brandclub-prod-mariadb:
    driver: overlay
    attachable: true
    name: brandclub-prod-mariadb

  # Application network (external to app stack)
  brandclub-prod-network:
    driver: overlay
    attachable: true
    name: brandclub-prod-network
