version: "3.8"

# =====================================================
# DATABASE STACK - STAGING
# =====================================================
# Only MariaDB - Redis in application stack
# =====================================================

services:
  mariadb:
    image: mariadb:10.6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max-connections=250
      - --innodb-buffer-pool-size=768M
      - --innodb-log-file-size=256M
      - --query-cache-size=0
      - --query-cache-type=0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - mariadb-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb-data:
    name: brandclub-staging-mariadb

networks:
  mariadb-network:
    name: brandclub-staging-mariadb
    driver: overlay
    attachable: true
