version: "3.8"

# =====================================================
# Portainer - Docker Swarm Management UI
# =====================================================
# Purpose: Manage multiple Docker Swarm stacks
# Features:
# - Web-based UI for stack management
# - Webhook support for CI/CD
# - Multi-environment management
# - RBAC and team management
# =====================================================

services:
  agent:
    image: portainer/agent:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == linux
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      LOG_LEVEL: INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer-agent

  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        # Traefik Configuration
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        
        # HTTP Router (redirect to HTTPS)
        - traefik.http.routers.portainer-http.rule=Host(`${PORTAINER_DOMAIN:-portainer.example.com}`)
        - traefik.http.routers.portainer-http.entrypoints=http
        - traefik.http.routers.portainer-http.middlewares=https-redirect
        
        # HTTPS Router
        - traefik.http.routers.portainer-https.rule=Host(`${PORTAINER_DOMAIN:-portainer.example.com}`)
        - traefik.http.routers.portainer-https.entrypoints=https
        - traefik.http.routers.portainer-https.tls=true
        - traefik.http.routers.portainer-https.tls.certresolver=le
        
        # Service definition (Portainer Web UI runs on 9000)
        - traefik.http.services.portainer.loadbalancer.server.port=9000
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - portainer-agent
      - traefik-public

volumes:
  portainer-data:
    name: portainer-data

networks:
  portainer-agent:
    driver: overlay
    attachable: true
    name: portainer-agent
  
  traefik-public:
    external: true
    name: traefik-public
