version: "3.7"
services:
  backup-sites:
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none

    image: registry.gitlab.com/c2k1/nms-erp:${VERSION}
    entrypoint: ["bash", "-c"]
    command:
      - |
        set -e
        backup_root=${BACKUP_DIR:-/backups}
        backup_dir=${backup_root}/$(date +%F)
        mkdir -p "$backup_dir"
        rm -rf sites/*/private/backups
        bench --site all backup --with-files
        if ls sites/*/private/backups >/dev/null 2>&1; then
          cp -r sites/*/private/backups/* "$backup_dir"/
        fi
        find "$backup_root" -mindepth 1 -maxdepth 1 -type d -mtime +7 -exec rm -rf {} +
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
      - "/backups:/backups"
    networks:
      - bench-network
      - mariadb-network

networks:
  bench-network:
    name: ${BENCH_NAME}
    external: true
  mariadb-network:
    name: ${MARIADB_NETWORK:-mariadb-network}
    external: true

volumes:
  sites:
    external: true
    # set to name of the sites volume
    name: ${SITES_VOLUME_NAME:-prod-nms-erp_sites}

# Set following environment variables
# VERSION
# BENCH_NAME
# MARIADB_NETWORK
# SITES_VOLUME_NAME
# BACKUP_DIR
