version: "3.7"

services:
  backend:
    image: registry.gitlab.com/c2k1/nms-erp:${VERSION}
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - mariadb-network
      - bench-network

  frontend:
    image: registry.gitlab.com/c2k1/nms-erp:${VERSION}
    command:
      - nginx-entrypoint.sh
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${BENCH_NAME:-erpnext}-http.rule=Host(`${SITES:?No sites set}`)
        - traefik.http.routers.${BENCH_NAME:-erpnext}-http.entrypoints=http
        - traefik.http.routers.${BENCH_NAME:-erpnext}-http.middlewares=https-redirect
        - traefik.http.routers.${BENCH_NAME:-erpnext}-https.rule=Host(`${SITES}`)
        - traefik.http.routers.${BENCH_NAME:-erpnext}-https.entrypoints=https
        - traefik.http.routers.${BENCH_NAME:-erpnext}-https.tls=true
        - traefik.http.routers.${BENCH_NAME:-erpnext}-https.tls.certresolver=le
        - traefik.http.services.${BENCH_NAME:-erpnext}.loadbalancer.server.port=8080
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: $$host
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - bench-network
      - traefik-public

  queue-default:
    image: registry.gitlab.com/c2k1/nms-erp:${VERSION}
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - mariadb-network
      - bench-network

  queue-long:
    image: registry.gitlab.com/c2k1/nms-erp:${VERSION}
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - mariadb-network
      - bench-network

  queue-short:
    image: registry.gitlab.com/c2k1/nms-erp:${VERSION}
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - mariadb-network
      - bench-network

  scheduler:
    image: registry.gitlab.com/c2k1/nms-erp:${VERSION}
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - mariadb-network
      - bench-network

  websocket:
    image: registry.gitlab.com/c2k1/nms-erp:${VERSION}
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - mariadb-network
      - bench-network

  migration:
    image: registry.gitlab.com/c2k1/nms-erp:${VERSION}
    deploy:
      restart_policy:
        condition: none
    entrypoint: ["bash", "-c"]
    command:
      - |
        bench --site all set-config -p maintenance_mode 1
        bench --site all set-config -p pause_scheduler 1
        bench --site all migrate
        bench --site all set-config -p maintenance_mode 0
        bench --site all set-config -p pause_scheduler 0
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - mariadb-network
      - bench-network

  redis-cache:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - bench-network

  redis-queue:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data
    networks:
      - bench-network

  redis-socketio:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-socketio-data:/data
    networks:
      - bench-network

volumes:
  db-data:

  redis-queue-data:
  redis-socketio-data:
  sites:
  logs:

networks:
  bench-network:
    name: ${BENCH_NAME:-erpnext}
    external: false
  mariadb-network:
    name: ${MARIADB_NETWORK:-mariadb-network}
    external: true
  traefik-public:
    name: traefik-public
    external: true

# Note: set VERSION, BENCH_NAME and SITES